// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPellets() {
  return window['go']['main']['GameEngine']['GetPellets']();
}

export function GetWallSkin() {
  return window['go']['main']['GameEngine']['GetWallSkin']();
}

export function GetGhosts() {
  return window['go']['main']['GameEngine']['GetGhosts']();
}

export function GetPlayerPosition() {
  return window['go']['main']['GameEngine']['GetPlayerPosition']();
}

export function GetState() {
  return window['go']['main']['GameEngine']['GetState']();
}

export function MovePlayer(arg1) {
  return window['go']['main']['GameEngine']['MovePlayer'](arg1);
}

export function ResetGhosts() {
  return window['go']['main']['GameEngine']['ResetGhosts']();
}

export function Restart() {
  return window['go']['main']['GameEngine']['Restart']();
}
